### PR TITLE
update ci workflow

### PR DESCRIPTION
**Pull request by yaswant**
### Update CI workflows

- implement build-group strategy 
- update test CMakeLists to always include coding norms

### Example build group annotation

build-group=JCSDA-internal/oops#2714

### CODE REVIEW

**Comment by yaswant** [comment]
I anticipate the manual workflow to work okay with manual trigger, but cant be tested until merged in develop.  I may need to open a follow-up PR in case the manual workflow proves problematic.

**Review by matthewrmshin — APPROVED** [review]
Looks sensible.

**Comment by yaswant** [comment]
@phlndrwd @odlomax - can you review this PR please?

**Comment by yaswant** [comment]
@phlndrwd note that monio tests still depend on legacy lfric-lite test data. Worth moving them to monio's own test suite or use cases from lfric-jedi instead?

**Comment by phlndrwd** [comment]
> @phlndrwd note that monio tests still depend on legacy lfric-lite test data. Worth moving them to monio's own test suite or use cases from lfric-jedi instead?

Thanks @yaswant. I guess this would be a trade-off between when the legacy data is due to disappear and when XIOS is expected to take-over from MONIO. If there is significant overlap then I don't think it would be worth making any significant changes here. Though I'm not in a position to answer this alone so it might be a conversation to be had with @odlomax, @matthewrmshin, & @mo-joshuacolclough, _et al_.

**Review by phlndrwd — APPROVED** [review]

**Review by odlomax — APPROVED** [review]

**Pull request merged**
