### PR TITLE
Detect netcdf-fortran.

### LINKED ISSUE #41: ecbuild failure to detect netcdf-fortran when building standalone.
Ecbuild fails when building standalone:

CMake Error at /home/h01/frwd/cylc-run/mi-be984/share/installs/ecbuild/share/ecbuild/cmake/ecbuild_add_library.cmake:308 (add_library):
  Target "monio" links to target "NetCDF::NetCDF_Fortran" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /home/h01/frwd/cylc-run/mi-be984/share/installs/ecbuild/share/ecbuild/cmake/ecbuild_add_library.cmake:667 (ecbuild_add_library_impl)
  src/CMakeLists.txt:59 (ecbuild_add_library)

### PR DESCRIPTION
**Pull request by DJDavies2**
I have added detection of netcdf-fortran in addition to netcdf-cxx.  Resolves #41.

### CODE REVIEW

**Review by mo-joshuacolclough — APPROVED** [review]

**Comment by phlndrwd** [comment]
Out of curiosity, @DJDavies2. Why does this change need to be made? MONIO does not use the Fortran NetCDF library. My feeling would be the issue is with the environment that is trying to build MONIO.

**Review by phlndrwd — COMMENTED** [review]
Added a general comment above.

**Comment by DJDavies2** [comment]
There could be a problem with the environment, but it is very unclear what the environment is supposed to be for these things.  If you have an idea for what should work I could try it and see what happens?

**Comment by phlndrwd** [comment]
> There could be a problem with the environment, but it is very unclear what the environment is supposed to be for these things. If you have an idea for what should work I could try it and see what happens?

Thanks @DJDavies2. I've sent you a meeting invite.

**Pull request merged**
